# name: CI - Build & Push to ECR

# on:
#   push:
#     branches: [ "main" ]

# env:
#   AWS_REGION: ap-south-1
#   ECR_REPOSITORY: strapi-app-repo
#   AWS_ACCOUNT_ID: 138383657644

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       # - name: Login to Amazon ECR
#       #   uses: aws-actions/amazon-ecr-login@v2

#       # - name: Build Docker image
#       #   run: |
#       #     docker build -t $ECR_REPOSITORY:${{ github.sha }} -f docker/Dockerfile ./Strapi-app

#       # - name: Tag Docker image
#       #   run: |
#       #     docker tag $ECR_REPOSITORY:${{ github.sha }} \
#       #     138383657644.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

#       # - name: Push image to ECR
#       #   run: |
#       #     docker push 138383657644.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

#       - name: Login to Amazon ECR
#   id: login-ecr
#   uses: aws-actions/amazon-ecr-login@v2

#       - name: Build and Push Docker image
#   run: |
#     IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

#     echo "Building image: $IMAGE_URI"

#     docker build -t $IMAGE_URI .
#     docker push $IMAGE_URI

name: CI - Build & Push to ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: strapi-app-repo
  AWS_ACCOUNT_ID: 138383657644

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          echo "Building image: $IMAGE_URI"

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
